#!/bin/sh
# Xiaomi AX9000 三频无线默认设置：在 Kwrt 的 10-wifi-detect 之后重新应用
[ "${ACTION}" = "add" ] || exit 0

(
    for i in $(seq 1 30); do
        [ "$(uci -q get base_config.@status[0].wifi)" = "1" ] && break
        sleep 1
    done

    for r in radio0 radio1 radio2; do
      uci set wireless.$r.disabled='0'
    done
    uci set wireless.default_radio0.disabled='0'
    uci set wireless.default_radio1.disabled='0'
    uci set wireless.default_radio2.disabled='0'
    uci set wireless.default_radio0.ssid='AA_2.4G'
    uci set wireless.default_radio0.encryption='psk2'
    uci set wireless.default_radio0.key='asd12345'
    uci set wireless.default_radio1.ssid='AA_5G'
    uci set wireless.default_radio1.encryption='psk2'
    uci set wireless.default_radio1.key='asd12345'
    uci set wireless.default_radio2.ssid='AA_5G_Game'
    uci set wireless.default_radio2.encryption='psk2'
    uci set wireless.default_radio2.key='asd12345'
    uci commit wireless
    /sbin/wifi up
) &
exit 0