#!/bin/sh
# Xiaomi AX9000 首次启动：LAN / 关闭 IPv6 / NCSI。无线由 30-ax9000-wifi 热插拔脚本按 band+path 配置。

# LAN 地址（list 语法，带 /24）
uci -q del network.lan.ipaddr
uci add_list network.lan.ipaddr='192.168.100.1/24'

# 关闭 IPv6
uci -q delete network.wan6
uci -q delete network.lan.ip6assign
uci -q delete network.globals.ula_prefix
uci set dhcp.lan.dhcpv6='disabled'
uci set dhcp.lan.ra='disabled'
uci set dhcp.lan.ndp='disabled'

# Windows NCSI 联网检测
uci add_list dhcp.@dnsmasq[0].address='/www.msftconnecttest.com/192.168.100.1'
uci add_list dhcp.@dnsmasq[0].address='/www.msftncsi.com/192.168.100.1'
uci add_list dhcp.@dnsmasq[0].address='/dns.msftncsi.com/131.107.255.255'

uci commit
exit 0